---
default_language_version:
  python: python3.11

repos:
  # Modify files
  ## YAML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [yaml]

  ## Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint-fix
        args: [--dot]

  ## INI
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]

  ## Python
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--config, .black.toml]

  ## All
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  # Checks
  ## YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--strict]

  ## YAML, JSON
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-metaschema
        name: Check YAML and JSON files against their schema
        exclude: ^\.github/workflows/[^/]*\.ya?ml$
      - id: check-github-workflows

  ## TOML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml

  ## Python
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.1
    hooks:
      - id: pylint
        additional_dependencies:
          - selenium==4.15.2
          - undetected-chromedriver==3.5.4
          - aiohttp[speedups]==3.9.0
          - frozendict==2.3.9
          - beautifulsoup4==4.12.2

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--ini, setup.cfg]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - dlint==0.14.1
          - flake8-bugbear==23.9.16
          - flake8-pie==0.16.0
          - flake8-simplify==0.21.0
          - wemake-python-styleguide==0.18.0
          - flake8-2020==1.8.1
          - flake8-async==22.11.14
          - flake8-encodings==0.5.0.post1
          - flake8-secure-coding-standard==1.4.0
          - flake8-string-format==0.3.0
          - flake8-warnings==0.4.1
          - flake8-mutable==1.2.0
          - flake8-comprehensions==3.14.0
          - flake8-datetimez==20.10.0
          - flake8-literal==1.3.0
          - flake8-newspaper-style==0.4.3
          - flake8-return==1.2.0
          - flake8-SQL==0.4.1
          - tryceratops==2.3.2
          - flake8-no-implicit-concat==0.3.5
          - flake8-use-fstring==1.4
          - flake8-use-pathlib==0.3.0
          - flake8-no-pep420==2.7.0
          - flake8-variables-names==0.0.6
          - flake8-annotations-complexity==0.0.8
          - flake8-cognitive-complexity==0.1.0
          - flake8-expression-complexity==0.0.11
          - flake8-comments==0.1.2
          - flake8-executable==2.1.3
          - flake8-noqa==1.3.2
          - flake8-sphinx-links==0.2.2
          - flake8-tidy-imports==4.10.0
          - flake8-type-checking==2.5.1
          - flake8-aaa==0.17.0
          - flake8-assertive==2.1.0
          - flake8-mock==0.4
          - flake8-pytest-style==1.7.2
          - flake8-annotations==3.0.1
          - flake8-new-union-types==0.4.1
          - flake8-pep585==0.1.7
          - flake8-future-annotations==1.1.0

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.337
    hooks:
      - id: pyright

  - repo: https://github.com/twu/skjold
    rev: v0.6.1
    hooks:
      - id: skjold
        args: [-s, pyup, -s, gemnasium, -s, pypa, -s, osv]
        files: ^requirements\.txt$

  ## All
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.0.0
    hooks:
      - id: cspell

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        args: [--assume-in-merge]
