---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaries:
  - python
words:
  - aiohttp
  - beatififulsoup
  - bestudemydeals
  - bungcip
  - leveryth
  - cardinalby
  - certi
  - crey
  - datetimez
  - davidanson
  - dlint
  - dotenv
  - esbenp
  - fstring
  - gemnasium
  - ggshield
  - idownloadcoupon
  - kolkata
  - palombini
  - ucupones
  - udemycoures
  - coures
  - pickler
  - pietro
  - pylance
  - pypa
  - pyright
  - pyrightconf
  - pyup
  - pyupgrade
  - skjold
  - subudemyfreebies
  - tamasfe
  - tryceratops
  - tzdata
  - udemy
  - Udemycodes
  - udemyfreebies
  - ufcwc
  - undetectability
  - unpickler
  - wemake
  - yarl
ignorePaths:
  - typings
  - .git
enableGlobDot: true
allowCompoundWords: true
useGitignore: true
